[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "inter-info"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "grpcio>=1.83.1",
    "grpcio-tools>=1.83.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "numpy>=2.5.2",
    "openmeteo-requests>=1.7.5",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
    "requests-cache>=1.3.3",
    "retry-requests>=2.0.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
    "structlog>=26.1.0",
    "pandas-stubs~=3.0.5",
    "pytest>=9.1.1",
]
[tool.fastapi]
entrypoint = "app.main:app"

[tool.setuptools.packages.find]
include = ["app*"]
